import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import prisma from "@/lib/prisma";
import { Sidebar } from "@/components/sidebar/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  const projects = await prisma.project.findMany();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-row">
          <Sidebar projects={projects} />
          <main className="flex-1 p-2 md:p-8 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
